### PR TITLE
Toggle timeout and auto close timeout option

### PR DESCRIPTION
**Pull request by theoomoregbee**
- reduced the toggle timeout(so users dont feel like the try it when one is open means toggle) , see commit , working on stacking of toast so users can just enable it from the options , instead of toggling it comes on top of the previous (no time to finish it , busy, so i left it out)
- added timeout option **time** so you can toggle automatically when the settimeout timing specified is reached

### CODE REVIEW

**Comment by delino12** [comment]
Nice one Theo. i've just add new updates using webpack4.

**Comment by theoomoregbee** [comment]
@delino12 really which repo ?

**Comment by delino12** [comment]
Its just a W.I.P, i'm rebuilding... it's from the repository i fork.

**Comment by theoomoregbee** [comment]
nice 👍

**Pull request closed without merging**
